#!/usr/bin/env python3
import os, subprocess, json, argparse
from pathlib import Path
import xml.etree.ElementTree as ET

VIDEO_EXTS = ('.mp4', '.mov', '.m4v', '.mxf', '.avi', '.mkv')

def parse_frame_duration(s):
    if s.endswith("s"): s = s[:-1]
    if "/" in s:
        num, den = s.split("/")
        return int(num), int(den)
    else:
        val = float(s)
        denom = round(1.0/val) if val > 0 else 25
        return 1, denom

def format_duration(frames, num, den):
    return f"{frames*num}/{den}s"

def seconds_to_frames(sec, num, den):
    return int(round(sec*den/num))

def get_duration(path):
    try:
        cmd = ['ffprobe','-v','error','-show_entries','format=duration',
               '-of','json',str(path)]
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              text=True, check=True)
        return float(json.loads(proc.stdout)["format"]["duration"])
    except:
        return None

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--folders","-f",default="sorted_folders.txt")
    parser.add_argument("--out","-o",default="output.fcpxml")
    parser.add_argument("--base","-b",default=".")
    parser.add_argument("--fallback-duration",type=float,default=5.0)
    parser.add_argument("--no-ffprobe",action="store_true")
    args = parser.parse_args()

    base = Path(args.base)
    num, den = parse_frame_duration("1/25s")

    # --- Build XML ---
    fcpxml = ET.Element("fcpxml", version="1.13")
    resources = ET.SubElement(fcpxml, "resources")

    # Video format
    ET.SubElement(resources, "format", id="r1", name="FFVideoFormat1080p25",
                  frameDuration="1/25s", width="1920", height="1080",
                  colorSpace="1-1-1 (Rec. 709)")

    # Add Gradient – Edge effect ONCE
    ET.SubElement(resources, "effect", id="r3", name="Gradient - Edge",
                  uid=".../Titles.localized/Lower Thirds.localized/Gradient - Edge.localized/Gradient - Edge.moti")

    library = ET.SubElement(fcpxml, "library")
    event = ET.SubElement(library, "event", name="AutoGenerated")
    project = ET.SubElement(event, "project", name="Merged Project")
    sequence = ET.SubElement(project, "sequence", duration="0s", format="r1",
                             tcStart="0s", tcFormat="NDF", audioLayout="stereo", audioRate="48k")
    spine = ET.SubElement(sequence, "spine")

    # Read folder order
    folders = []
    with open(args.folders,"r",encoding="utf-8") as f:
        for line in f:
            line=line.strip()
            if not line: continue
            parts=line.split(",",1)
            folders.append(parts[1].strip() if len(parts)==2 else parts[0].strip())

    asset_id = 4  # start after r3
    offset_frames = 0

    for idx, folder in enumerate(folders, start=1):
        folder_path = base/folder
        if not folder_path.exists(): continue
        vids = sorted([p for p in folder_path.iterdir() if p.suffix.lower() in VIDEO_EXTS])
        if not vids: continue

        folder_frames = 0
        assets = []

        for v in vids:
            dur=None
            if not args.no_ffprobe: dur=get_duration(v)
            if dur is None: dur=args.fallback_duration
            frames=seconds_to_frames(dur,num,den)
            folder_frames+=frames

            aid=f"r{asset_id}"
            asset_id+=1
            a=ET.SubElement(resources,"asset",id=aid,name=v.name,start="0s",
                            duration=format_duration(frames,num,den),
                            hasVideo="1",format="r1")
            ET.SubElement(a,"media-rep",kind="original-media",src=v.resolve().as_uri())
            assets.append((aid,frames,v))

        clip_start=offset_frames
        for i,(aid,frames,v) in enumerate(assets):
            off=format_duration(clip_start,num,den)
            dur=format_duration(frames,num,den)
            clip_elem=ET.SubElement(spine,"asset-clip",name=v.name,offset=off,ref=aid,
                                    duration=dur, tcFormat="NDF", audioRole="dialogue")

            if i==0:
                # Insert Title overlaying this folder's total duration
                title=ET.SubElement(clip_elem,"title",ref="r3",lane="1",offset="0s",
                                    name="Gradient - Edge", start="3600s",
                                    duration=format_duration(folder_frames,num,den))

                # Name text (folder name)
                t1=ET.SubElement(title,"text")
                ts1=ET.SubElement(t1,"text-style",ref=f"ts1_f{idx}")
                ts1.text=folder

                # Description text (empty)
                t2=ET.SubElement(title,"text")
                ts2=ET.SubElement(t2,"text-style",ref=f"ts2_f{idx}")
                ts2.text=""

                # Local text-style-defs
                ts1def=ET.SubElement(title,"text-style-def",id=f"ts1_f{idx}")
                ET.SubElement(ts1def,"text-style",font="Futura",fontSize="58",
                              fontFace="Medium", fontColor="0.989974 0.99019 0.98994 1")
                ts2def=ET.SubElement(title,"text-style-def",id=f"ts2_f{idx}")
                ET.SubElement(ts2def,"text-style",font="Futura",fontSize="37",
                              fontFace="Medium", fontColor="0.989974 0.99019 0.98994 1")

            clip_start+=frames

        offset_frames+=folder_frames

    sequence.set("duration",format_duration(offset_frames,num,den))

    # --- Save file ---
    ET.indent(fcpxml,space="  ")
    with open(args.out,"w",encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE fcpxml>\n')
        f.write(ET.tostring(fcpxml,encoding="unicode"))

    print(f"✅ Wrote {args.out}")

if __name__=="__main__":
    main()
